on: [workflow_dispatch, pull_request]

name: TEST

jobs:
  pull_and_push_images_to_gcp_registry:
    name: build
    runs-on: ubuntu-latest
    env:
      REGISTRY: "europe-west3-docker.pkg.dev/crucial-matter-351210/docker, europe-central2-docker.pkg.dev/round-axiom-360411/test"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Setup Gcloud    
      uses: google-github-actions/setup-gcloud@v0

    - name: Login to Gcloud Registry
      id: login-to-ar
      run: |
        gcloud auth configure-docker europe-central2-docker.pkg.dev,europe-west3-docker.pkg.dev --quiet
        echo $GITHUB_EVENT_NAME
    
    - name: Get list of existing images
      run: |
        a=($(echo "$REGISTRY" | tr ',' '\n'))
        for element in "${a[@]}"
        do
            file_name="$(cut -d'/' -f2 <<<"$element")"
            echo "${file_name}.json"
            gcloud artifacts docker images list $element --format=json --include-tags > "${file_name}.json"
        done

    - name: Run script
      run: |
        pip install -r requirements.txt
        python3 .github/check.py
